name: Go
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: install hugo
      run: |
        go get -u github.com/gohugoio/hugo
        go install github.com/gohugoio/hugo

    - name: setup public repo
      run: |
          git clone --depth 1 https://knsh14:${{ secrets.GITHUB_TOKEN }}@github.com/knsh14/test-repo-two.git knshsample/public

    - name: Build
      run: |
        export PATH=$PATH:`go env GOPATH`/bin
        cd knshsample && hugo

    - name: Push
      run: |
        export MSG=`git log --format=%B -n 1 HEAD`
        cd knshsample/public
        git add .
        git commit -m $MSG
