name: Issue
on:
  issues:
    types: [opened, edited]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Create CLI Command
      run: |
        echo github.context.issue.number
