name: Issue
on:
  issues:
    types: [opened, edited]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Create CLI Command
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
